global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'ingestion-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['ingestion-service:8080']

  - job_name: 'dashboard-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['dashboard-service:6677']

  - job_name: 'traffic-analysis-service'
    static_configs:
      - targets: ['traffic-analysis-service:8000']
